### ISSUE TITLE
Driver improvements

### ISSUE THREAD

**Issue by xiaoqiangwang** [djvine/ADTucsen#2]
I started to use this driver for a Dhyana 95 camera and improved the driver a bit, especially added trigger support.
https://github.com/xiaoqiangwang/ADTucsen
I did not create a PR just yet because the changes are extensive may not be your like.

**Comment by djvine** [comment]
Hi Xiaoqiang,

Your code looks good to me. Go ahead and create the PR and I will accept it.

Thanks for the effort. Are they using Tucsen camera at SLS?

David
